### ISSUE TITLE
screenshots

### ISSUE THREAD

**Issue by jpcy** [jpcy/xatlas#1]
![charts](https://user-images.githubusercontent.com/3744372/43034066-53a62dee-8d18-11e8-9767-0b38ed3fa2d3.png)
![charts_thumbnail](https://user-images.githubusercontent.com/3744372/43034067-5c09c1da-8d18-11e8-8490-25770f05e8e0.png)

**Comment by jpcy** [comment]
![viewer](https://user-images.githubusercontent.com/3744372/55389351-c7563000-5580-11e9-8161-fbba8f2f7c2f.png)
![viewer_thumbnail](https://user-images.githubusercontent.com/3744372/55389376-d0df9800-5580-11e9-9bea-f35f63349489.png)

**Comment by jpcy** [comment]
![CesiumMilkTruck_pack_random](https://user-images.githubusercontent.com/3744372/68638607-d4db8b80-054d-11ea-8238-845d94789a2d.gif)
![CesiumMilkTruck_pack_bruteforce](https://user-images.githubusercontent.com/3744372/68638614-da38d600-054d-11ea-82d9-43e558c46d50.gif)

**Comment by BrunoLevy** [comment]
![xatlas](https://user-images.githubusercontent.com/19478253/69903392-c0deb900-1398-11ea-8a52-c211bc7803a9.gif)
xatlas in Graphite/Geogram

**Comment by jpcy** [comment]
![viewer](https://user-images.githubusercontent.com/3744372/69908460-48323800-143e-11ea-8b18-58087493c8e9.png)
![viewer_thumb](https://user-images.githubusercontent.com/3744372/69908461-48cace80-143e-11ea-8b73-efea5a9f036e.png)
![godot tps](https://user-images.githubusercontent.com/3744372/69908462-48cace80-143e-11ea-8946-a2c596ec8028.png)
![godot tps thumb](https://user-images.githubusercontent.com/3744372/69908463-48cace80-143e-11ea-8035-b669d1a455f6.png)
