### ISSUE TITLE
enhancement packing charts

### ISSUE THREAD

**Issue by PerspectivesLab** [jpcy/xatlas#100]
Hi there, 
i can see charts are arranged based on their surface:  bigger charts would mean more surface in the map:
https://github.com/jpcy/xatlas/blob/ec707faeac3b95e6b416076a9509718cce105b6a/source/xatlas/xatlas.cpp#L8321

while adding multiple UV meshes and packing them,  i figured out that small surfaces can have bigger charts, than bigger surfaces  [(see picture with representation as real surface )](https://i.postimg.cc/rybk6Yf4/example.jpg)
how could i prevent this behaviour, and that all chart can respect their proportional surfaces ?
nb: i am using default parameters in the packing options.
thank you

**Comment by jpcy** [comment]
For UV meshes, surface area and parametric area are the same, so there's no scaling by surface area done there.

If all your UV meshes are normalized (0 to 1 range), they will all be given the same proportional area in the atlas. You would need to scale each mesh UV channel by whatever the  mesh scale is supposed to be.

**Comment by PerspectivesLab** [comment]
ok i understand UvMeshes can't make the corelation: chart->surfaceArea VS chart->parametricArea,
simply because UV meshes dont have access to mesh vertices and thus can't/won't calculate the surface area.

https://github.com/jpcy/xatlas/blob/ec707faeac3b95e6b416076a9509718cce105b6a/source/xatlas/xatlas.cpp#L8258

since i have access to triangle vertices positions before adding them to the UvMesh, i will calculate the surface area and scale before adding them to the uv mesh, thx
