### ISSUE TITLE
Is it possible to get the texture from the UV construction?

### ISSUE THREAD

**Issue by lthiet** [jpcy/xatlas#101]
I am using Python bindings to create a mesh with UV mapping from 3d scans. For each point, I have an associated color and with open3d I managed to make a colored mesh.

![image](https://user-images.githubusercontent.com/26815719/154969544-a119397c-6f62-45ed-875e-7cfdb62a5345.png)

Now I am using Atlas to generate UV mapping, but I don't know how I can get a texture from it so I can use it in Unity for example.

Do you know how I could do that?

**Comment by jpcy** [comment]
Rasterize each triangle in UV space. Rasterization must be conservative. At each texel centroid, use the barycentric coordinates to interpolate vertex colors. That gives you a UV coordinate for the texture, and a color to assign to it. Every lightmap generator does this, but for worldspace position and normals, not color - the same concept applies. You can do it in software or hardware.

Example: [Lightmapper](https://github.com/ands/lightmapper) - also used in the viewer [here](https://github.com/jpcy/xatlas/blob/master/source/viewer/viewer_bake.cpp)
