### ISSUE TITLE
Using the packer with existing segmentation and UVs

### ISSUE THREAD

**Issue by BrunoLevy** [jpcy/xatlas#14]
I got an already segmented / already parameterized mesh. Now I would like to use the packer with this existing segmentation and parameterization.

MeshDecl has vertexUvData and vertexUvStride, but it seems they are ignored when I'm calling xatlas::Generate(). I also tryed calling xatlas::PackCharts, but it fails with the message "ComputeCharts should be called first".

**Comment by jpcy** [comment]
This isn't currently supported, but I'll add it.

MeshDecl uvs are used by charting to take into account uv seams.

**Comment by BrunoLevy** [comment]
OK, makes sense, thank you for the clarification !

I managed to do something by adding a couple of function (without knowing exactly what I'm doing, but it seems to work), I will send a pull request once I make it clean enough.

**Comment by jpcy** [comment]
Done. Just call `AddUvMesh` to add meshes and `PackCharts` to pack them all.

Here's what packing 10 copies of the same mesh looks like: ![output_charts00](https://user-images.githubusercontent.com/3744372/58761018-8f6c6880-8582-11e9-99ac-c5da2d68acb1.png)
