### ISSUE TITLE
Build fails on Visual Studio 2015, works on 2017+

### ISSUE THREAD

**Issue by akien-mga** [jpcy/xatlas#21]
See godotengine/godot#30129 and build log on AppVeyor CI using Visual Studio 2015: https://ci.appveyor.com/project/akien-mga/godot/builds/25592281

Apparently the library builds fine against VS 2017. CC @fire.

Given Godot's big userbase we try to support VS 2015 as min version, even though 2017 or later is recommended (or even MinGW with latest GCC and LTO for best performance). So if xatlas can be made to build against VS 2015 without too much hassle, that would be great for our use case :)

**Comment by jpcy** [comment]
I'll fix this and setup CI so the build doesn't break in the future.

**Comment by jpcy** [comment]
[Fixed](https://ci.appveyor.com/project/jpcy/xatlas)

**Comment by akien-mga** [comment]
Thanks!

**Comment by fire** [comment]
Thanks for following up on this.
