### ISSUE TITLE
xatlas usage is limited to one core

### ISSUE THREAD

**Issue by fire** [jpcy/xatlas#22]
<jpcy\> Multithreaded tasks aren't very finely grained at this  point. A single mesh where all faces are connected will only use one  core. I should be able to improve that soon, but I need to swap out the  current task scheduler with one that can create sub tasks from any  thread first.

Make xatlas use the full power of the computer.

**Comment by saml1er** [comment]
I second this.

**Comment by fire** [comment]
Is this ready to test?

**Comment by jpcy** [comment]
No. There's still more things I can move to multithreaded tasks.

**Comment by jpcy** [comment]
There's more things I could move to tasks, but that's enough for now. If CPU usage is still limited to one core then there's something wrong.

**Comment by fire** [comment]
Seems to use all the cores on my computer. Looks good.

**Comment by fire** [comment]
f65a664c5b8eb81ae7cc92b6dd9da54b0840a6bf
