### ISSUE TITLE
Avoid texture duplication in repack example

### ISSUE THREAD

**Issue by saml1er** [jpcy/xatlas#23]
I know that you (jpcy) warned me about repack duplicating the same textures multiple times. I tried using the example with bigger models, and the resultant texture atlases were immensely bigger in size than original. 

Is it very difficult to use material ids to avoid duplication of the same texture? Duplicating the same texture 2-3 times is fine, but duplicating it like 20 times is a problem. I really wasn't expecting this. 😥

Just use example_repack for this model, and then check the texture size (56 megabytes), while the sum of original file sizes is less then 200 KB: 
[cj_bag_reclaim.zip](https://github.com/jpcy/xatlas/files/3360736/cj_bag_reclaim.zip)

I'm generating atlases for at least 4000 models and now, imagine having 50mb+ textures per model. 

If this is very difficult to implement, then please add me on discord (saml1er#8752), I can offer something in return if you can resolve this.

**Comment by jpcy** [comment]
Tiling/repeating UVs don't work with atlasing. There's no way around that. A chart with extents of (0,0) to (10,1) takes up 10 times as much space in the atlas as another chart with extents of (0,0) to (1,1).

**Comment by saml1er** [comment]
@jpcy You're right, my bad. Not all textures need to be of high quality. I forgot that I can also use `texelsPerUnit` and setting the value to 0.7 helped a lot in reducing the texture size.
