### ISSUE TITLE
xatlas::PackCharts crash

### ISSUE THREAD

**Issue by saml1er** [jpcy/xatlas#28]
xatlas::PackCharts crashes when the resolution is set to something specific. At times, the crash doesn't happen at all. You can use this model to reproduce the crash: [clump_output.zip](https://github.com/jpcy/xatlas/files/3413991/clump_output.zip)

It is easier to reproduce the crash if you compile it in debug mode. The crash can happen anywhere.
`ASSERT: texcoord.x >= 0 && texcoord.y >= 0 C:\Users\danish\Documents\Git\Github\Repositories\saml1er\xatlas\xatlas.cpp 7268`
`XA_DEBUG_ASSERT(chart->allowRotate);`
`XA_DEBUG_ASSERT(index < m_size);` <---- from Array class

To reproduce: 
```
uint32_t GetBestAtlasMaxResolution(xatlas::Atlas* atlas)
{
    uint32_t maxResolution = std::max(atlas->width, atlas->height);
    while (maxResolution % 4 != 0)
    {
        maxResolution++;
    }
    return maxResolution;
}

xatlas::SetPrint(printf, true);
xatlas::Atlas* atlas = xatlas::Create();

if (!AddMeshesToAtlas(atlas, model, uvs)) { return EXIT_FAILURE; }

xatlas::PackOptions packOptions;
packOptions.createImage = true;
packOptions.padding = 1;
packOptions.texelsPerUnit = 1.0f;
xatlas::PackCharts(atlas, packOptions);

// Get 4x4 resolution for DXT 1
uint32_t bestAtlasReslotution = GetBestAtlasMaxResolution(atlas);
printf("packing charts again with resolution: %d\n", (int)bestAtlasReslotution);

xatlas::Destroy(atlas);
atlas = xatlas::Create();
if (!AddMeshesToAtlas(atlas, model, uvs)) { return EXIT_FAILURE; }

packOptions.resolution = bestAtlasReslotution;
xatlas::PackCharts(atlas, packOptions);
```
Full code (modified example_repack): https://pastebin.com/mdZq6YH7

**Comment by jpcy** [comment]
I fixed the assert that was supposed to catch this case (chart not fitting in the atlas). bestAtlasReslotution needs + 2 for padding since one of the charts takes up the full atlas width.

**Comment by saml1er** [comment]
> 
> 
> I fixed the assert that was supposed to catch this case (chart not fitting in the atlas). bestAtlasReslotution needs + 2 for padding since one of the charts takes up the full atlas width.

Thanks, that helped. In some cases, I had to increase the size by 100 because it kept crashing. Instead of assertation, can we use enums? #29

**Comment by jpcy** [comment]
>In some cases, I had to increase the size by 100 because it kept crashing.

That shouldn't happen. Do you have a model I can use to reproduce that?

Also, if all you need is atlas dimensions to be divisible by 4, it's not necessary to pack charts again. Instead, divide by the dimensions you want when normalizing texture coordinates [here](https://github.com/jpcy/xatlas/blob/master/extra/example_repack.cpp#L794).

**Comment by saml1er** [comment]
> 
> That shouldn't happen. Do you have a model I can use to reproduce that?
> 

It's fixed in the latest version. Thank you.
 
> Also, if all you need is atlas dimensions to be divisible by 4, it's not necessary to pack charts again. 

I can, but I'm packing again to check if the new atlas size is generating more than one atlas, if it is, then I increase the resolution to get a single atlas.

Btw, I found a new crash. I have around 14000 models, and xatlas crashes on 5 models. Here's one of them:

[LowLODModel.zip](https://github.com/jpcy/xatlas/files/3435670/LowLODModel.zip)

**Comment by saml1er** [comment]
Nice, it's fixed now except for one model: 
[freeway6_lan2.zip](https://github.com/jpcy/xatlas/files/3438113/freeway6_lan2.zip)
This one seems to crash on xatlas::PackCharts.

**Comment by saml1er** [comment]
I didn't check the newer commits. Everything's working now. Thanks a lot.
