### ISSUE TITLE
Make it more fault-tolerant

### ISSUE THREAD

**Issue by reduz** [jpcy/xatlas#3]
I think I am honestly not very interested in knowing which vertex or face failed and why. Most users just download models from the web and try them out, and I think they should work anyway. 

Simply drop the faces that are broken and bake without them, or pack them as separate charts or whatever. At this point, the original thekla did a better job by continuing ( I can unwrap original Sponza fine with thekla, but not with xatlas).

**Comment by reduz** [comment]
I mean, in real life, the artist will see that something looks bad after it baked, will go see the geometry, realize something is odd in there and fix it. There is no need to fail unwrap because of this.

**Comment by reduz** [comment]
Ah I see, most of the time the problem is "already added edge". I think in this case, the face should be added anyway, unconnected to other faces so its packed separate but still work.

**Comment by jpcy** [comment]
I don't think the thekla_atlas example setup colocal vertices properly, which is why is works with Sponza. There's a small note about that in [the header](https://github.com/jpcy/xatlas/blob/master/xatlas.h#L163). 

The fundamental problem is the half-edge mesh data structure needs to make sense. It really only works with manifold meshes.

**Comment by guycalledfrank** [comment]
I have at least 2 meshes that produce broken output (one is full NaNs, another is 90% zeros and two normal charts). No warnings/errors. Not sure how to approach debugging that. Is it a good idea to send these meshes to you to test?

**Comment by jpcy** [comment]
Send them to me and I'll have a look.

**Comment by guycalledfrank** [comment]
Cool, sent you an email

**Comment by jpcy** [comment]
This was fixed a long time ago now. I ended up dropping the half-edge mesh representation in favor of simple arrays and handling non-manifold geometry by splitting meshes on duplicate edges. Any invalid geometry (zero length edges, etc.) still exists in the output meshes, with uvs set to 0.
