### ISSUE TITLE
Asserts extents > realMaxChartsize

### ISSUE THREAD

**Issue by fire** [jpcy/xatlas#34]
https://github.com/jpcy/xatlas/blob/93cf61df1883f42e66e434d11026ea661e2f402d/xatlas.cpp#L7102

I'm getting asserts where the value is close to one of the other value but slightly over:

Tried doing this, but do you have an approximately equals function that is scaled by the values?

XA_DEBUG_ASSERT(unsigned int(extents.x) <= realMaxChartSize && unsigned int(extents.y) <= realMaxChartSize);

Edited:

Trialing:

```
XA_DEBUG_ASSERT(!(extents.x > realMaxChartSize && extents.x - realMaxChartSize > FLT_EPSILON || extents.y > realMaxChartSize && extents.y - realMaxChartSize > FLT_EPSILON));
```
This doesn't work.

**Comment by fire** [comment]
What happens to -1 near the limits?

https://github.com/jpcy/xatlas/blob/93cf61df1883f42e66e434d11026ea661e2f402d/xatlas.cpp#L7091

**Comment by fire** [comment]
```cpp
			if (maxChartSize > 0) {
				const float realMaxChartSize = (float)maxChartSize - 1.0f; // Aligning to texel centers increases texel footprint by 1.
				if (extents.x > realMaxChartSize || extents.y > realMaxChartSize) {
					if (warnChartResized)
						XA_PRINT("   Resizing chart %u from %gx%g to %ux%u to fit atlas\n", c, extents.x, extents.y, maxChartSize, maxChartSize);
					scale = realMaxChartSize / max(extents.x, extents.y);
					extents.x = extents.y = 0.0f;
					for (uint32_t i = 0; i < chart->uniqueVertexCount(); i++) {
						Vector2 &texcoord = chart->uniqueVertexAt(i);
						texcoord *= scale;
						extents = max(extents, texcoord);
						extents.x = roundevenf32(extents.x);
						extents.y = roundevenf32(extents.y);
					}
					XA_DEBUG_ASSERT(extents.x <= realMaxChartSize && extents.y <= realMaxChartSize);
				}
			}
```

**Comment by fire** [comment]
@jpcy Can you comment?

**Comment by jpcy** [comment]
What is scale and extents when you hit that assert? It's probably a float precision issue.

**Comment by jpcy** [comment]
Should be fixed now. I just clamp to maximum. Don't need the assert then - it was only there to detect precision problems.
