### ISSUE TITLE
too slowly in generating atlas when the mesh faces is huge

### ISSUE THREAD

**Issue by hs5530hs** [jpcy/xatlas#36]
I have a mesh of 1000K faces, it spend about 12 hours to generate the atlas. so it would be much better if you can sped up this ^ ^.

**Comment by jpcy** [comment]
There's a performance issue with meshes that contain many unconnected pieces of geometry that I need to investigate and fix. That's probably what's occurring here. A workaround in the meantime is to merge all geometry into a single mesh (i.e. so you only call `xatlas::AddMesh` once).

**Comment by jpcy** [comment]
Try latest. I fixed all the obvious performance bottlenecks I could find with large meshes.

**Comment by BachiLi** [comment]
FYI, I have some meshes with ~1M faces from 3D reconstruction algorithms that I used this library for UV mapping. It often takes really long inside the `mergeCharts` phase (I never was patient enough to see it finish). If I set `XA_MERGE_CHARTS` to 0 it takes ~10 minutes to generate an atlas.

**Comment by jpcy** [comment]
Send any problem models to me if you can. It's a lot easier to fix issues if I can reproduce them.

**Comment by BachiLi** [comment]
Thanks! You can download a mesh here: https://drive.google.com/open?id=1O-LnYdJiSXo8TwcJIclPCJakCwEx6JJQ (37.7 Mb).

**Comment by JoshMeier** [comment]
I've got another mesh that takes longer to unwrap than one would expect given its size:

`mesh 0: 2520 vertices, 3554 triangles, 66 charts`
`Generated atlas in 375.45 seconds (375453 ms) `

On the release build of the current master (e12ea82d16abb08b3a4875a6064318e801123db6) with default settings in the viewer. The model is quite far from the origin, but even after centering the model, it still takes the same amount of time. Is the model just very unfortunate? I have attached it as a zipped obj file:
[long_unwrap_duration.zip](https://github.com/jpcy/xatlas/files/4116607/long_unwrap_duration.zip)

**Comment by JoshMeier** [comment]
I seem to have found another model which has a long unwrap time on current master (6bafcfa5cd0f10b1cbf837baffe9cd71fa525113) with default settings in the viewer for a Release build. It took 304243ms to unwrap at 6457 vertices and 6493 triangles: 
[unwrap_304243.zip](https://github.com/jpcy/xatlas/files/4192973/unwrap_304243.zip)

**Comment by Murazaki** [comment]
We're having issues with meshes obtained from 3D reconstruction with xatlas.
They're kind of dirty (non-manifold issues, mesh not closed and sometimes scattered faces, ...)
What would you recommend to avoid getting stuck in atlas generation ?

[dirty-mesh.zip](https://github.com/jpcy/xatlas/files/5246805/dirty-mesh.zip)

**Comment by jpcy** [comment]
The mesh segmentation algorithm isn't really suited to large high-poly meshes with no hard seams like that.

You could try mesh simplification. Run xatlas on the simplified mesh, then project the parameterization back to the original mesh.
