### ISSUE TITLE
Document UV convention

### ISSUE THREAD

**Issue by hugoam** [jpcy/xatlas#4]
The UV provided in the output seem to be relative the bottom-left corner and not top-left, am I correct ?
It would be nice to mention this somewhere explicitly ! Just to avoid some head-scratching

**Comment by jpcy** [comment]
48b06f3

**Comment by hugoam** [comment]
Sorry, I don't know exactly what I had been smoking but... the above issue I opened doesn't make any sense at all after all.
The coordinates output by xatlas are relative to the axes x and y of the input rectangle, and that's it, there is no notion of bottom or top, my bad for introducing that confusion in the first place 😕
