### ISSUE TITLE
Assertion failure for model

### ISSUE THREAD

**Issue by JoshMeier** [jpcy/xatlas#40]
On the current master (34011835ab9e13d7a292e84ca9e44af68284e880) I seem to have problems when unwrapping a certain model. It triggers Array's `XA_DEBUG_ASSERT(index < m_base.size);` assertion during the convex hull calculation while adding charts, but it seems the actual cause could be nans getting in during the LSCM in the parametrization step (or something else, at least that's how far I was able to track down the issue). 

The only options I changed from the default options were setting bilinear to false, setting resolution to 1024, padding to 2 and max chart size to 1024. This is how my settings look in the viewer:
![my options](https://user-images.githubusercontent.com/48955730/69222148-281a9300-0b79-11ea-8df5-6c687dd834ef.PNG)

I have also attached the model here:
[nan_error.zip](https://github.com/jpcy/xatlas/files/3868081/nan_error.zip)

**Comment by jpcy** [comment]
Should be fixed now.

Charts for that model are quite bad with default settings, as are most models with a lot of different planes of curvature. Lowering "max threshold" gives better results.
