### ISSUE TITLE
Can I set the intervalbetween the two charts?

### ISSUE THREAD

**Issue by KeepFaithMe** [jpcy/xatlas#41]
Hello:
I have a quzzle.
I have a mesh, and I use your tool 'xalats'computing the  chart,but when computed,I found taht the charts is too close,so I want ask you whether I can set the interval between charts,
please give ne some advice.Thank you!

**Comment by Kuranes** [comment]
The padding parameter of PackOptions is exaclty for that 
https://github.com/jpcy/xatlas/blob/master/xatlas.h#L210
