### ISSUE TITLE
How to handle the flip triangle?

### ISSUE THREAD

**Issue by KeepFaithMe** [jpcy/xatlas#44]
Hello
     When I use the xatlas to compute my mesh,I find something wrong.Firstly, my mesh is oblique photogrammetry model, so the mesh is not close.I found that in the console show that :(1)failed to closed holes;(2)doesn't have disk topology;(3)invalid parameterization, self-intersecting boundary;(4)invalid parameterization, 2 / 78 flipped triangles.I am confused.because of aboved ,there are many charts with invalid parameterizations.
   So I want ask:(1)whether the mesh must close? (2) is the xatlas tool can handle the flip triamgle?
looking forward to you reply? thank you again.

**Comment by jpcy** [comment]
It's unlikely you will get good results from photogrammetry models. The mesh segmentation algorithm is suited to simple game environments with large areas of mostly coplanar faces that parameterize well. Photogrammetry models are much noisier.
