### ISSUE TITLE
texture resolution limit

### ISSUE THREAD

**Issue by malytomas** [jpcy/xatlas#45]
Hi,
I am trying to unwrap a mesh and I expect it to split into multiple meshes with one texture each with limited resolution.
I set the PackOptions::resolution to the maximum resolution (number of pixels on one side) of the texture, eg. 512, and I set the PackOptions::texelsPerUnit to the ratio of model distance to texel width, eg. 0.1 (that is 10 pixels per 1 unit distance).

I get just one mesh (altough with multiple charts), but the uv coordinates are totally weird. The uv coordinates are in range like 35 to 45. And the charts are next to each other instead of overlapping in the same texture space.
The Atlas::with and height is at the value that I set in the resolution most of the time, but I also noticed that sometimes they are few pixels larger.

I have also noticed PackOptions::maxChartSize now, is that related to my problem? I do not understand what units does it limit. Is it pixels or number of charts or something else?

Thanks for any help and explanation.

**Comment by jpcy** [comment]
>I set the PackOptions::texelsPerUnit to the ratio of model distance to texel width, eg. 0.1 (that is 10 pixels per 1 unit distance).

That should be 10, not 0.1. I think that's your main problem here.

uvs aren't normalized, so they will be in 0-511 range for a 512x512 resolution atlas. `Vertex::atlasIndex` or `Chart::atlasIndex` is the third component, i.e. the texture index. Two charts with a different `atlasIndex` can have overlapping uvs.

**Comment by malytomas** [comment]
> That should be 10, not 0.1. I think that's your main problem here.

Thanks, That was the solution. I think I have assumed that the resolution sets upper bound and that xatlas would reduce the resolution, which it does not and it is ok.

---

Anyway, this setting:
```c++
		xatlas::PackOptions pack;
		pack.resolution = 512;
		pack.texelsPerUnit = 10;
		pack.padding = 2;
		pack.bilinear = true;
		pack.blockAlign = true;
```
will change the resolution to 516, which I think is a legitimate issue.

**Comment by malytomas** [comment]
Awesome. Thanks
