### ISSUE TITLE
too many charts

### ISSUE THREAD

**Issue by cdcseacave** [jpcy/xatlas#47]
Great project! However, even on small meshes, it generates way too many charts, most of which are very small. Is there a way to control this or it is an intrinsic issue of the algorithm?

![image](https://user-images.githubusercontent.com/2802670/73734827-ed230700-4746-11ea-97bc-238feaca0002.png)

[mesh.zip](https://github.com/jpcy/xatlas/files/4152615/mesh.zip)

**Comment by jpcy** [comment]
The mesh segmentation algorithm only really works well on fairly simple meshes with close to planar surfaces. It's also not possible to determine whether parameterizations will be valid or not (LSCM can have triangle flips), and the fallback method I'm using isn't fully implemented and tends to generate a lot of small charts.

Lowering "max threshold" a little and switching to OpenNL LSCM may help, but probably not enough to get good results from that mesh.
