### ISSUE TITLE
Weird UV charts generation

### ISSUE THREAD

**Issue by JustAndreww** [jpcy/xatlas#48]
Hello!

Here is the original OBJ file: https://we.tl/t-g6LNxfOi8o (35 MB ZIP, 200 MB OBJ, 1M tris).

On some surfaces weird-looking charts are being generated: 
![image](https://user-images.githubusercontent.com/4374611/73734808-ce396a80-4770-11ea-906a-3ede34440bf1.png)

I'm using viewer with default settings (via **Generate** button). I've tried to adjust some of the parameters, but it will anyway appear on the different surfaces.

Is there any way to improve charts generation? Box projection mapping?

Thanks!

**Comment by jpcy** [comment]
Setting `XA_RECOMPUTE_CHARTS` to `0` [here](https://github.com/jpcy/xatlas/blob/master/xatlas.cpp#L118) will fix that, but you will have some charts with invalid parameterizations instead.

**Comment by JustAndreww** [comment]
Thanks for the advice. Setting `XA_RECOMPUTE_CHARTS` to `0` improves initial OBJ file charts generation in some places:
![image](https://user-images.githubusercontent.com/4374611/73817045-95ef6600-481c-11ea-8271-9d031ffc1f22.png)

We've also tried to experiment with geometry a bit. OBJ file has hard normals everywhere, so we added smooth in some areas to fix it.  New file (FBX) can be found here: https://we.tl/t-gWBNY8Rjpg (37 MB ZIP, 52 MB FBX).

With this FBX file chars looks distorted as well, but differently:
![image](https://user-images.githubusercontent.com/4374611/73817636-0fd41f00-481e-11ea-9252-34fcfcc23007.png)

So, if I understand correctly, there is no mode to generate chars via box projection / cube projection mapping?

**Comment by jpcy** [comment]
Those are invalid parameterizations. Switching to OpenNL LSCM may give slightly better results. Beyond that, there's nothing else that can be done, besides manually cleaning up charts in a modelling program.

There's no box projection. The mesh segmentation/charting algorithm grows faces using a bunch of metrics. Parameterization uses LSCM.

**Comment by JustAndreww** [comment]
Thanks for the clarifications. Do you have any plans to implement box projection in the future?

**Comment by jpcy** [comment]
Maybe. Detecting when it's appropriate to use on an arbitrary mesh is the hard part.
