### ISSUE TITLE
Remove lightmapper related comment in obj file

### ISSUE THREAD

**Issue by ands** [jpcy/xatlas#5]
https://github.com/jpcy/xatlas/blob/4cf7f147d42ba6b70d468f05578b3a0ac491c022/gazebo.obj#L1

Since this is not part of my lightmapper example, you could remove the first line of the obj file, because that was a comment about the corresponding example lightmap size :)

Cool project!

**Comment by jpcy** [comment]
5d38bf6

Thanks. Great job on your lightmapper project. I used it as a base for experimenting with [global ray bundles (PDF)](https://pdfs.semanticscholar.org/7970/af3ce40d5db10afe86db1beeb0fe61a2400d.pdf), which is what the screenshot on the right is from.
