### ISSUE TITLE
No UV charts is being generated on a very small object

### ISSUE THREAD

**Issue by JustAndreww** [jpcy/xatlas#50]
Maybe that's an expected behavior for file with such dimensions?

```
Computing charts
   0 charts
Parameterizing charts
   0 planar charts, 0 ortho charts, 0 LSCM charts, 0 piecewise charts
Packing 0 charts
Building output meshes
   mesh 0: 8457 vertices, 2819 triangles, 0 charts
```

[cable_0.zip](https://github.com/jpcy/xatlas/files/4163395/cable_0.zip)

**Comment by jpcy** [comment]
All faces are detected as having zero area. Scaling the mesh should fix that.

**Comment by JustAndreww** [comment]
Yeah, that what I thought initially.
Thanks!
