### ISSUE TITLE
optimize packing into multiple atlases for frustum culling

### ISSUE THREAD

**Issue by malytomas** [jpcy/xatlas#53]
Hi,
I use xatlas to unwrap and split a large mesh into multiple smaller meshes with textures that fulfill opengl limitations on resolution.
Is it also possible to configure the packing algorithm to pack charts that are close to each other in model space to be in same atlas?
This would allow to use frustum culling to skip rendering of some meshes. It may also improve texture cache utilization in gpu.
Thanks

**Comment by jpcy** [comment]
That should be possible, but it's too obscure for me to implement and maintain. You can do that in your own fork.
