### ISSUE TITLE
vertexCount in atlas is less than the actual vertex count

### ISSUE THREAD

**Issue by oschakravarthi** [jpcy/xatlas#56]
For some meshes, the vertexCount is less than the actual vertex count (meshDecl.vertexCount)
For example, I have a mesh with 92 vertices. but in the atlas output, the vertex count is 90.
I am updating the UVs of original mesh with the atlas UVs using xref. 
Now for the missing vertices, I dont have UVs.

How to handle this case?
Should I re-write the original mesh?

**Comment by jpcy** [comment]
If you can send me the mesh or post it here I can investigate further. None of my test models have output vertex counts lower than input.

Chart edges add UV seams to a mesh, so the vertex count should be larger than the input mesh. Index count doesn't change, but indices do - to point to the new vertices. You can't just update input mesh vertices alone. See [the example](https://github.com/jpcy/xatlas/blob/master/extra/example.cpp#L240).

**Comment by oschakravarthi** [comment]
Hi, 

I am in deep trouble.
I have a mesh with one UV channel (which is used for diffuse texture/image)
I want to generate a second UV channel for Ambient Occlusion. I am using xatlas for generating this. 

After generating atlas, if I update the vertices and indices of the mesh based on the atlas values, the diffuse texture is not shown properly. 
I am re-ordering the using the below code but ambient image is not shown properly as the order of indices in xatlas output is different from the original indices of the mesh. 

Unfortunately, we cannot specify indices for each UV channel. What should I do?

Can we ask xatlas to generate atlas with the same indices order?

Please help me. Thanks in advance.

   
```
const xatlas::Mesh &mesh = atlas->meshes[0];
  size_t new_vertices_count = mesh.vertexCount;

  float atlas_width = (float)atlas->width;
  float atlas_height = (float)atlas->height;

  std::vector<Vector2> *uvs = new std::vector<Vector2>();

  Vector2 empty(0, 0);
  uvs->reserve(original_vertices_count);
  for (uint32_t v = 0; v < original_vertices_count; v++) {
    uvs->push_back(empty);
  }
  for (uint32_t v = 0; v < new_vertices_count; v++) {
    const xatlas::Vertex &vertex = mesh.vertexArray[v];
    Vector2 uv(vertex.uv[0] / atlas_width, vertex.uv[1] / atlas_height);
    size_t xref = vertex.xref;
    uvs->at(xref) = uv;
  }
```

**Comment by oschakravarthi** [comment]
Hi,

I am in deep trouble.
I have a mesh with one UV channel (which is used for diffuse texture/image)
I want to generate a second UV channel for Ambient Occlusion. I am using xatlas for generating this.

After generating atlas, if I update the vertices and indices of the mesh based on the atlas values, the diffuse texture is not shown properly.
I am re-ordering the UVs of the generated channel in the vertices order of the mesh (code below) but ambient image is not shown properly as the order of indices in atlas output is different from the original indices of the mesh.

Unfortunately, we cannot specify indices for each UV channel. What should I do?

Can we ask xatlas to generate atlas with the same indices order and vertices of the original mesh?

Please help me. Thanks in advance.

```
const xatlas::Mesh &mesh = atlas->meshes[0];
  size_t new_vertices_count = mesh.vertexCount;

  float atlas_width = (float)atlas->width;
  float atlas_height = (float)atlas->height;

  std::vector<Vector2> *uvs = new std::vector<Vector2>();

  Vector2 empty(0, 0);
  uvs->reserve(original_vertices_count);
  for (uint32_t v = 0; v < original_vertices_count; v++) {
    uvs->push_back(empty);
  }
  for (uint32_t v = 0; v < new_vertices_count; v++) {
    const xatlas::Vertex &vertex = mesh.vertexArray[v];
    Vector2 uv(vertex.uv[0] / atlas_width, vertex.uv[1] / atlas_height);
    size_t xref = vertex.xref;
    uvs->at(xref) = uv;
  }

```

**Comment by jpcy** [comment]
You need to use the geometry from `xatlas::Mesh` and use `xatlas::Vertex::xref` to copy any vertex attributes (e.g. position, normal, uv1 channel) from the source mesh, like the example. Index order *is* preserved, but since new vertices are added on chart seams, some indices will point to new vertices (with xref of the original vertex). You're trying to do things backwards - copying xatlas UVs to the original mesh - which won't work.
