### ISSUE TITLE
Simpler roundness metric decreasing utilization

### ISSUE THREAD

**Issue by JoshMeier** [jpcy/xatlas#57]
Since the introduction of the simpler roundness metric (551e2e7252a64407628dc656a8683d1668dea81d), I seem to have a problem with a decrease in utilization in a large amount of models. An extreme example would be this cylinder model, which goes from 77% when reverting the commit on the current master (bf395a40a94d6a00ad99121ec1507bb703a47e25) to 22% with the commit included: 
[curvature_issue_example.zip](https://github.com/jpcy/xatlas/files/4324332/curvature_issue_example.zip).

I have tried to combat this by using parameters, but thus far have been unable to "revert" the change introduced by the new roundness metric for a general purpose case with either the roundness weight or the straightness weight. I hoped that maybe you could offer insight into what these changes mean and what I could do to adapt my unwrapping in order to regain some utilization.

**Comment by jpcy** [comment]
This was actually a packing bug, the metric changes just caused it to manifest.
