### ISSUE TITLE
Mesh with multiple materials.

### ISSUE THREAD

**Issue by oschakravarthi** [jpcy/xatlas#60]
Hi,
xatlas is a great library. Thanks a lot.

I have a question.

In my model, a mesh can have more than one material. Different material can be applied to each triangles. How should I handle this case?

Thanks in advance

**Comment by jpcy** [comment]
You don't need to do anything. Nothing in the library cares about materials.

**Comment by oschakravarthi** [comment]
> You don't need to do anything. Nothing in the library cares about materials.

Thanks for your reply.

Does it mean that I cannot use xatlas for meshes with multiple materials?

**Comment by jpcy** [comment]
No. You can have 1 material or 1,000,000. It doesn't matter. There's no concept of materials in the library.

If you mean [the example code here](https://github.com/jpcy/xatlas/blob/master/extra/example.cpp#L240), it only writes geometry for simplicity - you can change it write whatever else you want from the input model. Faces are in the same order as input.

**Comment by oschakravarthi** [comment]
Hi,

"Faces are in the same order as input" - The will be same but the vertices are re-ordered/added. 
Lets say, I have 6 vertices {v1, v2, v4, v4, v5, v6} and 2 triangles. {0,1,2}, {3, 4, 5}. First triangle uses material m1 and second one uses m2.
In the atlas mesh, the indices might be same but the vertices could be {v4, v5, v6, v1,v2,v3}.

Am I wrong?

**Comment by jpcy** [comment]
That's right. Use `xatlas::Vertex::xref` to copy attributes (e.g. position, normal, uv0) from the old vertex to the new one, [like this](https://github.com/jpcy/xatlas/blob/master/extra/viewer_atlas.cpp#L625).

**Comment by oschakravarthi** [comment]
Thanks for your reply.
Lets assume that the original data and xatlas data are as shown in the diagram.
In xatlas output, indices order and count are same. Vertices are same but order is different.
If xatlas gives output like this, there is no way I can color/material my triangles. I can do it only if xatlas output contains the same set of triangles that are in input.

Please confirm whether xatlas outputs the same set of triangles as input or not.

Thanks

![image](https://user-images.githubusercontent.com/29388049/80857435-cd30b000-8c6f-11ea-980d-7260a0f63d6e.png)

**Comment by jpcy** [comment]
Sponza and other models with multiple materials all work fine for me. If you have a model that reproduces the problem in the viewer project I'll look at it. I can't blindly debug your problems for you.

**Comment by oschakravarthi** [comment]
Hi,

Here is my simple validation check.
For each triangle in atlas mesh, checking whether that triangle exist in the original mesh or not.

It is failing for my meshes. Please help me in solving the problem

  for (int i = 0; i < atlas_mesh.indexCount; i += 3) {
    int i0 = atlas_mesh.vertexArray[atlas_mesh.indexArray[i]].xref;
    int i1 = atlas_mesh.vertexArray[atlas_mesh.indexArray[i + 1]].xref;
    int i2 = atlas_mesh.vertexArray[atlas_mesh.indexArray[i + 2]].xref;

    bool matching_triangle_found = false;

    for (int j = 0; j < original_mesh.indices.size(); j += 3) {
      int j0 = original_mesh.indices[j];
      int j1 = original_mesh.indices[j + 1];
      int j2 = original_mesh.indices[j + 2];

      if (i0 == j0) {
        if ((i1 == j1 && i2 == j2) || (i1 == j2 && i2 == j1)) {
          matching_triangle_found = true;
          break;
        }
      }
      if (i0 == j1) {
        if ((i1 == j0 && i2 == j2) || (i1 == j2 && i2 == j0)) {
          matching_triangle_found = true;
          break;
        }
      }

      if (i0 == j2) {
        if ((i1 == j0 && i2 == j1) || (i1 == j1 && i2 == j0)) {
          matching_triangle_found = true;
          break;
        }
      }
    }

    if (!matching_triangle_found) {
      std::cout << "No matching triangle found in the original geometry";
    }
  }

**Comment by oschakravarthi** [comment]
I think, I need to use AddUvMesh

**Comment by oschakravarthi** [comment]
Hi @jpcy 

Thanks a lot for the continuous support. 
As you said earlier,  I could perfectly re-position all other vales like vertices, all existing uv channels, normals etc. of my mesh based on the xref. Everything works fine.

In my mesh, I have a  `std::vector<int> face_material_indices.`
The material number of each triangle is stored in this set.
I could not understand the logic to update this set; If I leave it unchanged, the mesh is not displayed properly. Materials mixed up.

I have tried in different ways but it is not working for me.
I have gone thru all the sample code but could not get understand what I am doing wrong.

Do you have a code snipped which maps materials? 

Please help me in this. If I cannot achieve this, I am dead.

**Comment by oschakravarthi** [comment]
Dear @jpcy ,

Sorry for annoying you. It looks like I could not communicate my problem without ambiguity.
Code will not have any ambiguity.
Here is my code to update the original mesh from xatlas. It is a small code. May I request you to have a quick check?

Thanks in advance.

```
void UVUnwrapper::apply_atlas(ccl::Mesh &cycles_mesh, const AtlasResult &atlas_result)
{
  //Cycles mesh is a triangu mesh. It has fields:
  //verts - std::vector<float3>. It will have vertices 
  //indices - std::vector<uint32_t>. It will have indices
  //material_indices - std::vector<uint32_t>. It will have material id of each triangle. Ie, it will have  
  //indices.size()/3 elements.
  //attributes - UVs, Normals, VertexColors, Tangents etc will be there.
  
  Atlas &atlas = *atlas_result.atlas;
  int original_vertices_count = cycles_mesh.verts.size();
  xatlas::Mesh &atlas_mesh = atlas.meshes[0];
  int new_vertex_count = atlas_mesh.vertexCount;
  int index_count = atlas_mesh.indexCount;
  int triangles_count = index_count / 3;

  size_t float3_size = sizeof(float3);

  //Taking backup of vertices
  float3 *original_verts_data = new float3[original_vertices_count];
  memcpy(original_verts_data, cycles_mesh.verts.data(), float3_size * original_vertices_count);

  //Cycles mesh will have Normals, UVs, Vertex colors etc in attributes.
  //An attrubute will have N elements where N is the number of vertices. 
  //Element size varies. For Normals attribute the element size if sizeof(float3). For VertexColor attribute, the Element size is sizeof(color)
  
  //Taking backup of attributes
  int attributes_count = cycles_mesh.attributes.attributes.size();
  std::vector<char *> buffer_backups;
  buffer_backups.resize(0);
  buffer_backups.reserve(attributes_count);

  ccl::AttributeSet &attributeset = cycles_mesh.attributes;
  for (auto it = attributeset.attributes.begin(); it != attributeset.attributes.end(); it++) {
    const ccl::Attribute &attribute = *it;

    int element_size = attribute.data_sizeof();
    int original_buffer_size = original_vertices_count * element_size;
    char *original_buffer_backup = (char *)malloc(original_buffer_size);
    memcpy(original_buffer_backup, attribute.buffer.data(), original_buffer_size);
    buffer_backups.push_back(original_buffer_backup);
  }
  
  //Resize cycles_mesh  
  cycles_mesh.resize_mesh(new_vertex_count, triangles_count);

  float3 *new_verts_data = cycles_mesh.verts.data();

  //Update the vertices with the value at xref location from the backup 
  for (int i = 0; i < new_vertex_count; i++) {
    xatlas::Vertex &atlas_vertex = atlas_mesh.vertexArray[i];
    int xref = atlas_vertex.xref;
    new_verts_data[i] = original_verts_data[xref];
  }
  delete[] original_verts_data;

  //Update attributes from backup
  int attribute_index = 0;
  for (auto it = attributeset.attributes.begin(); it != attributeset.attributes.end(); it++) {
    ccl::Attribute &attribute = *it;
    char *original_buffer_backup = buffer_backups[attribute_index];
    size_t element_size = attribute.data_sizeof();

    char *buffer = attribute.buffer.data();

	//Update attribute with the value at xref location from the backup 
    for (int i = 0; i < new_vertex_count; i++) {
      xatlas::Vertex &atlas_vertex = atlas_mesh.vertexArray[i];
      uint32_t xref = atlas_vertex.xref;

      char *original_value_position = original_buffer_backup + (xref * element_size);
      char *new_value_position = buffer + (element_size * i);
      memcpy(new_value_position, original_value_position, element_size);
    }

    free(original_buffer_backup);
    attribute_index++;
  }

  //Create a new UV attribute to store the UVs given by XAtlas 
  ustring atlas_uv_attribute_name("_dnt_generated_");
  ccl::Attribute *uvs_attribute = cycles_mesh.attributes.add(AttributeStandard::ATTR_STD_UV, atlas_uv_attribute_name);
  float2 *uvs_data = uvs_attribute->data_float2();

  float atlas_width = atlas.width;
  float atlas_height = atlas.height;

  //Populate the newly created UV attribute from the UVs given by XAtlas 
  for (int i = 0; i < new_vertex_count; i++) {
    xatlas::Vertex &atlas_vertex = atlas_mesh.vertexArray[i];
    float2 &uv = make_float2(atlas_vertex.uv[0] / atlas_width, atlas_vertex.uv[1] / atlas_height);
    uvs_data[i] = uv;
  }

  cycles_mesh.atlas_uv_attribute_name = atlas_uv_attribute_name;
  cycles_mesh.atlas_width = atlas_width;
  cycles_mesh.atlas_height = atlas_height;
}

```
