### ISSUE TITLE
Black lines on edges

### ISSUE THREAD

**Issue by oschakravarthi** [jpcy/xatlas#62]
Hi,

I am using XAtlas to generate UV channels for my models. When I bake those models in a baking software, I am getting black lines on edges. Can I do anything in my UV channel generation logic to avoid these lines? or it is the problem from the baking application?

![image](https://user-images.githubusercontent.com/29388049/82759389-c0385400-9e0a-11ea-9427-3531f1071e0b.png)

**Comment by jpcy** [comment]
That's the responsibility of the baking software. Some require padding around charts and run a dilate filter on the baked texture. Others don't require padding and dilate texels that would be sampled by bilinear filtering. The default pack options are for the latter. For the former, you can set padding [here](https://github.com/jpcy/xatlas/blob/master/xatlas.h#L201), and set `blinear` to false to pack a little more optimally.

**Comment by oschakravarthi** [comment]
Thank you @jpcy for responding.
While building Atlas, I am not providing any Normals data. My mesh has only Face-Normals. It has no vertex normals. It is not a problem right If I dont provide Normals to xatlas?

**Comment by jpcy** [comment]
That's fine - vertex normals are optional.

**Comment by oschakravarthi** [comment]
Hi@jpcy

Thanks a lot for your continuous support.
I have fixed the black line stuff at baking side but there is some other problem.

I have a sofa mesh. I have generating UV channel for this using xatlas and exported it. 

When I import it into Blender, this is how it t is shown in the viewport.
 
You can see the patches on pillows in the below image. It is not a rendered image. This is from viewport.  It looks like xatlas is treating two triangle as co-planar when the angle between their normals is less than a threshold. To avoid this, some parameters I need to set I think. There are some settings in ChartOptions but not sure what exactly to set.

Can you please help me in this? This is the last thing I need to fix in my product.

Thanks in advance.   

![image](https://user-images.githubusercontent.com/29388049/82853920-a25f1200-9f24-11ea-953f-f37bf384dc29.png)

**Comment by jpcy** [comment]
That doesn't look like it has anything to do with xatlas.

**Comment by oschakravarthi** [comment]
Hi @jpcy 

Does xatlas treat two triangle as co-planar when the angle between their normals is less than a threshold? I think it does.

**Comment by fynv** [comment]
> That's the responsibility of the baking software. Some require padding around charts and run a dilate filter on the baked texture. Others don't require padding and dilate texels that would be sampled by bilinear filtering. The default pack options are for the latter. For the former, you can set padding [here](https://github.com/jpcy/xatlas/blob/master/xatlas.h#L201), and set `blinear` to false to pack a little more optimally.

Hi @jpcy, I'm starting to use xatlas recently and I don't quite get it why we don't need padding & dialte when sampling by bilinear filtering. The black texels may still contribute to some UV points, won't they?

**Comment by fynv** [comment]
Is it some trick using pre-multiplied alpha?
