### ISSUE TITLE
Model stuck during unwrap

### ISSUE THREAD

**Issue by JoshMeier** [jpcy/xatlas#63]
I seem to have found another model that gets stuck during chart computation on the current master (470576d3516f7e6d8b4554e7c941194a935969fd) with the default parameters in the viewer: 
[window_frame_model.zip](https://github.com/jpcy/xatlas/files/4680818/window_frame_model.zip)

**Comment by JoshMeier** [comment]
The referenced commit fixes the issue with the model I linked, the only issue I found that it increases unwrap time significantly for a model I previously had issues with:  [longer_unwrap_model.zip](https://github.com/jpcy/xatlas/files/4735302/longer_unwrap_model.zip)

Not sure if that is worth investigating, if not, the issue would be resolved for me. Either way, thanks a lot again!

**Comment by jpcy** [comment]
Performance for that model should be more reasonable now. Single charts with a large number (1000s) of faces still somewhat bottleneck performance though.
