### ISSUE TITLE
Can I use this library for generating Diffuse UV maps?

### ISSUE THREAD

**Issue by oschakravarthi** [jpcy/xatlas#64]
Hi,

Can I use this library for generating Diffuse UV maps?

**Comment by jpcy** [comment]
Yes.

**Comment by oschakravarthi** [comment]
Wow.. @jpcy  that's great.
My requirement is to generate two uv maps.
One for diffuse and other one for light map.
In the light map uv, the triangles can be placed anywhere based on best fit but for diffuse uv map, it is not the case.

The user can change the diffuse image (for example, a flower image). but still it should be displayed properly.

If this is possible, is there any example?

**Comment by jpcy** [comment]
In that case, no.
