### ISSUE TITLE
Viewer loads corrupt mesh

### ISSUE THREAD

**Issue by chpatrick** [jpcy/xatlas#65]
I'm getting strange results when loading [bunny.obj](https://graphics.stanford.edu/~mdfisher/Data/Meshes/bunny.obj):

![2020-06-30-003709_1355x764_scrot](https://user-images.githubusercontent.com/832719/86062856-e5535e80-ba69-11ea-8425-6cf38562a0ad.png)

This happens both on `4d9f80fe350a0768560723f61bdde8c2f7194daa` and `470576d3516f7e6d8b4554e7c941194a935969fd`. Built on NixOS.

**Comment by jpcy** [comment]
Works for me on Windows. Is that the only model that looks garbled for you?

**Comment by chpatrick** [comment]
No, all models seem to be wrong that I've tried. `example` produces correct output though.

**Comment by jpcy** [comment]
What's the console output? The number of triangles and vertices should be printed.

**Comment by chpatrick** [comment]
```
Loading 'bunny.obj'
   1 object
   1 mesh
   4968 triangles
   5362 vertices
```

**Comment by chpatrick** [comment]
`bunny.obj` has 2503 vertices though so it seems like some kind of parsing issue.

**Comment by jpcy** [comment]
Should be fixed now.

**Comment by chpatrick** [comment]
Yep, it works, thanks a lot!
