### ISSUE TITLE
Wrong scale when using an existing UV atlas

### ISSUE THREAD

**Issue by devernay** [jpcy/xatlas#67]
Hi,
At this line in the code: https://github.com/jpcy/xatlas/blob/master/xatlas.cpp#L8977

the scale is computed from a surface ratio, which seems wrong, as the scale is in linear units: if the surface ratio is 4, scale should be `sqrt(4)*m_texelsPerUnit`.

So the correct line should be:
```
scale = sqrt(chart->surfaceArea / chart->parametricArea) * m_texelsPerUnit;
```

Or did I misunderstand something?
Thanks you for that great piece of code

**Comment by jpcy** [comment]
You're right, nice catch.
