### ISSUE TITLE
How does a mesh generate multiple atlas?

### ISSUE THREAD

**Issue by KeepFaithMe** [jpcy/xatlas#69]
Dear Developer:
        I have a mesh (arbitrary magnitudes) that I want to generate multiple atlas(two or three). I have read your code and the examples you provided,but I still have no idea how to generate multiple atlases.So can you give me some advice,thank you!
       Looking forward to your reply!

**Comment by jpcy** [comment]
You need to set both `xatlas::PackOptions::texelsPerUnit` and `xatlas::PackOptions::resolution` to non-zero values. If a chart doesn't fit in the first atlas, a second one is created and the chart packed into it, and so on.

As an example, open the [gazebo model](https://github.com/jpcy/xatlas/blob/master/models/gazebo.obj) in the Viewer and set "Texels per unit" to 50, and "Resolution" to 512. That will generate 3 atlases.

**Comment by KeepFaithMe** [comment]
Thank you for your answer.I konw what parameter 'xatlas::PackOptions::resolution' does,but I am confused about the parameter xatlas::PackOptions::texelsPerUnit.It says in your notes:"Unit to texel scale. e.g. a 1x1 quad with texelsPerUnit of 32 will take up approximately 32x32 texels in the atlas.",to my understanding,when the texelsPerUnit = 32, a 1x1 quad will take up approximately 32x32 texels in the atlas.Is that correct? And what are the length and  width of the quad.What is the unit of the quad? Is meter?Or something else?

**Comment by jpcy** [comment]
Units mean whatever you want them to. If you model a building with 1 unit = 1 meter and you want 10 texels per meter, then set `xatlas::PackOptions::texelsPerUnit` to 10.
