### ISSUE TITLE
UV chart winding

### ISSUE THREAD

**Issue by holzon** [jpcy/xatlas#71]
Hi!
I have a problem with charts having flipped winding.

![xatlas](https://user-images.githubusercontent.com/22636760/87041789-0860d980-c1f3-11ea-9eb6-67405167be90.png)

Due to the baker that we use, charts need to have the same winding in UV. Is there any way to set this up with the options, or any hints at how I could hack xatlas to accomplish same winding for all charts?

**Comment by jpcy** [comment]
What's the baker you're using?

**Comment by holzon** [comment]
V-Ray standalone.
Normal maps do not bake correctly when the UV winding is inconsistent, havent found a workaround besides ensuring UV-mapping is consistent.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jpcy** [comment]
Setting `xatlas::ChartOptions::fixWinding` to true and `xatlas::PackOptions::rotateCharts` to false should enforce clockwise UV winding now (positive area). I should be able to change `rotateCharts` behavior so it doesn't need to be disabled in the future. Right now it flips x and y, reversing winding.

**Comment by holzon** [comment]
Nice!!

![xatlas2](https://user-images.githubusercontent.com/22636760/87224509-23b01e00-c386-11ea-9e3b-9e4d19cfea8f.png)

I'm a bit confused about the clockwise vs counter-clockwise winding, to my knowledge, most apps like Maya, 3ds max and obj file format is considered right hand/CCW as standard. When I was looking at the code, computeFaceNormal surprised me by looking very clock-wise to me as you say, not CCW as I had expected.

I'm a pretty happy guy now anyway, looks like the correct winding for me in the output, so totally fine with the way it works! 

Had an assert that didn't compile in debug, don't know if it's something you want to keep or not
xatlas.cpp, line 9314: error C2039: 'allowRotate': is not a member of 'xatlas::internal::pack::Chart

**Comment by jpcy** [comment]
Fixed that warning.
