### ISSUE TITLE
Is function ComputeCharts parallel computing?

### ISSUE THREAD

**Issue by KeepFaithMe** [jpcy/xatlas#74]
Hi :
    I have a question about the function 'ComputeCharts ' in the file  'xatlas.cpp',I want to konw whether the function ComputeCharts is parallel computing? This is very import to me,please tell me the answer.
    Looking forward to your reply!
    Thank you!

**Comment by jpcy** [comment]
Yes. it uses one thread per core, minus the main (calling) thread. How well threads are utilized depends mainly on how many models are added and whether they are composed of disconnected meshes.

If you set `XA_MULTITHREADED` to 0, only the main thread is used.
