### ISSUE TITLE
Patch is missing

### ISSUE THREAD

**Issue by KeepFaithMe** [jpcy/xatlas#75]
Hi:
   When I use the xatlas to Compute multiple meshes,the number of faces in all meshes will always miss some faces,what's wrong with it.I am confussed! If you know what's going on, please tell me.

**Comment by jpcy** [comment]
I need more information to help. A model to reproduce the problem would do.

**Comment by KeepFaithMe** [comment]
By reading your code, I am aware of the cause of this problem.So thank you for your reply!
