### ISSUE TITLE
Error: declaration shadows a variable

### ISSUE THREAD

**Issue by bmahlbrand** [jpcy/xatlas#79]
So, I have a trivial error when I integrate this into my project, it's easily fixed on my end, but curious if you're open to fixing it / accepting a PR upstream. If so, what would your preference be in addressing this? My current hack is to change `enum Enum` to `enum class Enum`, and updating the references to something like this: `ProgressCategory::Enum::BuildOutputMeshes`.

Error: declaration shadows a variable in namespace 'xatlas' [-Werror,-Wshadow]
Error: declaration shadows a variable in namespace 'xatlas' [-Werror,-Wshadow]
Error: declaration shadows a variable in namespace 'xatlas' [-Werror,-Wshadow]
```
// Progress tracking.
struct ProgressCategory
{
	enum Enum
	{
		AddMesh,
		ComputeCharts,
		ParameterizeCharts,
		PackCharts,
		BuildOutputMeshes
	};
};
```

**Comment by bmahlbrand** [comment]
I have one in a similar vein at xatlas.cpp:2221 `if (bucketCount == 8) h[4][*p++]++, h[5][*p++]++, h[6][*p++]++, h[7][*p++]++;
` when compiling 32 bit with array bounds checking turned on. Easily commented out for this particular build, but do you have thoughts on a better way to handle it with the macros?

**Comment by jpcy** [comment]
These should be fixed, but different compiler versions may give different warnings, so let me know if I missed any.

**Comment by bmahlbrand** [comment]
Thanks! The only other thing I had to do was fix `PackagingResults: Error: Expected xatlas.h to be first header included.` when packaging in ue4.
