### ISSUE TITLE
which is uv result

### ISSUE THREAD

**Issue by orangeagain** [jpcy/xatlas#85]
I assume chart is uv.
I try to create uvs in unity. but ouput zero chart. I don't know which part missing.
outputMesh's IndexCount and triangleCount is correct, but ChartCount is 0.
Would you give me some tips? thanks a lot
here is my c# code:
`

        Vector3[] points = input.vertices;
        GCHandle pinPoints = GCHandle.Alloc(points, GCHandleType.Pinned);
        IntPtr pointsIntPtr = pinPoints.AddrOfPinnedObject();

        int[] triangles = input.triangles;
        GCHandle pinTriangles = GCHandle.Alloc(triangles, GCHandleType.Pinned);
        IntPtr trianglesIntPtr = pinTriangles.AddrOfPinnedObject();

        var normals = input.normals;
        GCHandle pinNormals = GCHandle.Alloc(triangles, GCHandleType.Pinned);
        IntPtr normalsIntPtr = pinNormals.AddrOfPinnedObject();

        Debug.Log("paperVertices:" + triangles.Length + "triangles:" + triangles.Length + "normals:" + normals.Length);

        MeshDecl meshDecl = new MeshDecl
        {
            VertexCount = (uint)points.Length,
            VertexPositionData = pointsIntPtr,
            VertexPositionStride = sizeof(float) * 3,        
            IndexCount = (uint)triangles.Length,
            IndexData = normalsIntPtr,
            IndexFormat = (XAtlasSharp.IndexFormat)input.indexFormat
        };
        if (input.normals != null)
        {
            meshDecl.VertexNormalData = normalsIntPtr;
            meshDecl.VertexNormalStride = sizeof(float) * 3;
        }

        XAtlas.SetPrint(Myprint, true);
        Atlas atlas = Atlas.Create();
        var addMeshError = atlas.AddMesh(meshDecl);
        if (addMeshError != AddMeshError.Success)
            Debug.LogError("Xatlas load error:" + addMeshError.ToString());
        else
            Debug.Log("Xatlas locad success.");

        atlas.Generate();

        foreach (var xmesh in atlas.Meshes) {
            Debug.Log("xatlasMesh:ChartCount:" + xmesh.ChartCount+ " triangleCount:" + xmesh.IndexCount+ " vertCount:" + xmesh.VertexCount);
            Assert.AreEqual(triangles.Length, xmesh.IndexCount);
        }

        Debug.Log("Result:MeshCount:" + atlas.MeshCount + " AtlasCount:" + atlas.AtlasCount + " ChartCount:" + atlas.ChartCount
            + " Height:" + atlas.Height + "x" + atlas.Width);

`

**Comment by jpcy** [comment]
Not my C# bindings. Try asking the author.
