### ISSUE TITLE
How to do when vertices have more attributes，for example tangent, bitangent?

### ISSUE THREAD

**Issue by wityhb** [jpcy/xatlas#86]

**Comment by jpcy** [comment]
[Vertex::xref](https://github.com/jpcy/xatlas/blob/master/source/xatlas/xatlas.h#L64) cross-references the original vertex. Simply copy over any vertex attributes from that. [Example.](https://github.com/jpcy/xatlas/blob/master/source/examples/example.cpp#L326)
