### ISSUE TITLE
Avoid mesh edit for mesh instance support (feature request)

### ISSUE THREAD

**Issue by madrazo** [jpcy/xatlas#9]
I would like the option to keep the input and output meshes without changes (without adding new vertices to the new mesh), so the generated uvs can be drawn directly using a second stream without having to edit the original data.  This is useful if you want to use a single model with various instances.

The way I was thinking to achieve this is to "preprocess" the original mesh by generating a dummy lightmap of the single mesh and use the generated mesh for the second lightmap generation that includes other meshes in the scene.

Tried setting ChartOptions growFaceCount to 0 but no luck, it crashes.
Tried setting setting ChartOptions maxThreshold to 0 on the first pass and a large number on the second, and the vertex keeps constant, however the lightmap for a single cube is not generated correctly (it is correct when not setting maxThreshold on the second pass).

Also I see that the number of vertexes increases too much with maxThreshold =0.  

Any ideas would be appreciated

Furthermore, the option for keeping each mesh on a single lightmap would be desirable insead of splitting it on various lightmaps

Thanks!

**Comment by jpcy** [comment]
New vertices are added where chart edges create a seam, there's no way to avoid that, unless uv seams perfectly match normal seams, which isn't going to realistically happen.

The simplest way to handle multiple instances of the same model is to generate a single atlas, share it between all instances, but use a separate lightmap for each instance. If that would result in too many texture switches, you could rectangle pack them into a larger atlas and pass a 2D offset into a vertex shader.

**Comment by madrazo** [comment]
Thank you for your answer. That makes sense. 
Maybe I could still use PackCharts to generate the packed textures
