### ISSUE TITLE
About Chart Count

### ISSUE THREAD

**Issue by wityhb** [jpcy/xatlas#91]
Hi, thank for you project, is very powerful. Now i have a question. I want to control the count of charts. I had tried several ways which had been given, like set XA_RECOMPUTE_CHARTS = 0, or max threshold(i had not found it). The next question, i want to know the function of ChartOptions::useInputMeshUvs. In my opinion, if ChartOptions::useInputMeshUvs = True, then the result of uv layout is similar  to original model's uv layout. I don't know whether it's right. Thank for you help!

**Comment by wityhb** [comment]
if it is possible, It would be better to explain ChartOptions and Packoptions by an example.

**Comment by jpcy** [comment]
The number of charts isn't supposed to be directly configurable. The ChartOptions weights, maxCost and maxIterations probably shouldn't be in the API so ignore those. Beyond that, the documentation is in the code comments, examples and viewer. The best way to figure things out is to change options in the viewer and see what happens.
