### ISSUE TITLE
build for ios succeed,but link failed.

### ISSUE THREAD

**Issue by orangeagain** [jpcy/xatlas#92]
I import three source files in to xcode static library,and build successed.
output is *.a file. when build and link ios project, compile give some errors blow:
`[arm64] Linking UnityFramework... ld: warning: arm64 function not 4-byte aligned: _unwind_tester from Libraries\libiPhone-lib.a(unwind_test_arm64.o) Undefined symbols for architecture arm64: "_xatlasCreateAtlas", referenced from: _xatlas_xatlasCreateAtlas_m9F6FC3423AC0B1507184F8C09C95F46FB4BBF88F in Assembly-CSharp-firstpass.cpp.obj _xatlas_Unwrap_m802775D37FBE07E5D156FF53BF6A3DD5D49085E7 in Assembly-CSharp-firstpass.cpp.obj (maybe you meant: _xatlas_xatlasCreateAtlas_m9F6FC3423AC0B1507184F8C09C95F46FB4BBF88F) "_xatlasGetAtlasIndex", referenced from: _xatlas_xatlasGetAtlasIndex_m0CCAE558A035BA6441F9D7D2ED707375A098FAFF in Assembly-CSharp-firstpass.cpp.obj (maybe you meant: _xatlas_xatlasGetAtlasIndex_m0CCAE558A035BA6441F9D7D2ED707375A098FAFF) "_xatlasAddUVMesh", referenced from: _xatlas_xatlasAddUVMesh_m1F7FCBBD0147EF2F1DF7DAE8DBE5B5EFA9DF40BD in Assembly-CSharp-firstpass.cpp.obj (maybe you meant: _xatlas_xatlasAddUVMesh_m1F7FCBBD0147EF2F1DF7DAE8DBE5B5EFA9DF40BD) "_xatlasGetAtlasCount", referenced from: _xatlas_xatlasGetAtlasCount_m9A86D46FED32309AAADA55661D46680EA25960A3 in Assembly-CSharp-firstpass.cpp.obj (maybe you meant: _xatlas_xatlasGetAtlasCount_m9A86D46FED32309AAADA55661D46680EA25960A3) "_xatlasAddMesh", referenced from: _xatlas_xatlasAddMesh_mF5F0320F2B1860E6C215CDBFE6A2CE115FBE3B3E in Assembly-CSharp-firstpass.cpp.obj _xatlas_Unwrap_m802775D37FBE07E5D156FF53BF6A3DD5D49085E7 in Assembly-CSharp-firstpass.cpp.obj (maybe you meant: _xatlas_xatlasAddMesh_mF5F0320F2B1860E6C215CDBFE6A2CE115FBE3B3E) "_xatlasParametrize", referenced from: _xatlas_xatlasParametrize_m20F95ED4808596651DE0B1F0BF2A8FD83F51ADA7 in Assembly-CSharp-firstpass.cpp.obj _xatlas_Unwrap_m802775D37FBE07E5D156FF53BF6A3DD5D49085E7 in Assembly-CSharp-firstpass.cpp.obj (maybe you meant: _xatlas_xatlasParametrize_m20F95ED4808596651DE0B1F0BF2A8FD83F51ADA7) "_xatlasGetVertexCount", referenced from: _xatlas_xatlasGetVertexCount_m7DFA5121E9DD4387EDCAF2B7E220E2087AFB00D7 in Assembly-CSharp-firstpass.cpp.obj _xatlas_Unwrap_m802775D37FBE07E5D156FF53BF6A3DD5D49085E7 in Assembly-CSharp-firstpass.cpp.obj (maybe you meant: _xatlas_xatlasGetVertexCount_m7DFA5121E9DD4387EDCAF2B7E220E2087AFB00D7) "_xatlasClear", referenced from: _xatlas_xatlasClear_m8290FB30AD17F5CE7D5A78FA5421835177887D32 in Assembly-CSharp-firstpass.cpp.obj _xatlas_Unwrap_m802775D37FBE07E5D156FF53BF6A3DD5D49085E7 in Assembly-CSharp-firstpass.cpp.obj (maybe you meant: _xatlas_xatlasClear_m8290FB30AD17F5CE7D5A78FA5421835177887D32) "_xatlasPack", referenced from: _xatlas_xatlasPack_m05EFE7D4FC4FDFF567FF6A5699FF03915AD080C5 in Assembly-CSharp-firstpass.cpp.obj _xatlas_Unwrap_m802775D37FBE07E5D156FF53BF6A3DD5D49085E7 in Assembly-CSharp-firstpass.cpp.obj (maybe you meant: _xatlas_xatlasPack_m05EFE7D4FC4FDFF567FF6A5699FF03915AD080C5) "_xatlasNormalize", referenced from: _xatlas_xatlasNormalize_mB03652469DB319858DED018EAD3B1A0D0E8FD947 in Assembly-CSharp-firstpass.cpp.obj _xatlas_Unwrap_m802775D37FBE07E5D156FF53BF6A3DD5D49085E7 in Assembly-CSharp-firstpass.cpp.obj (maybe you meant: _xatlas_xatlasNormalize_mB03652469DB319858DED018EAD3B1A0D0E8FD947) "_xatlasGetIndexCount", referenced from: _xatlas_xatlasGetIndexCount_m4D35E2A4BCEB2CC07F6055B21F9006AA9662E833 in Assembly-CSharp-firstpass.cpp.obj _xatlas_Unwrap_m802775D37FBE07E5D156FF53BF6A3DD5D49085E7 in Assembly-CSharp-firstpass.cpp.obj (maybe you meant: _xatlas_xatlasGetIndexCount_m4D35E2A4BCEB2CC07F6055B21F9006AA9662E833) "_xatlasGetData", referenced from: _xatlas_xatlasGetData_m13F5E6596D6D1A4D7774A384FFF435C0D4F6518E in Assembly-CSharp-firstpass.cpp.obj _xatlas_Unwrap_m802775D37FBE07E5D156FF53BF6A3DD5D49085E7 in Assembly-CSharp-firstpass.cpp.obj (maybe you meant: _xatlas_xatlasGetData_m13F5E6596D6D1A4D7774A384FFF435C0D4F6518E) ld: 12 symbol(s) not found for architecture arm64`
I use unity to call xatlas static library function.
Do anyone has any suggestion for me?

**Comment by jpcy** [comment]
That's from unofficial c# bindings, nothing to do with me.
