### ISSUE TITLE
How to allow xatlas to split charts into smaller chunks for minimizing output atlas size

### ISSUE THREAD

**Issue by yongsiang-fb** [jpcy/xatlas#97]
I am trying to use the UVMesh to repack some textures into a new one. During the process I found that xatlas does not tend to add texture seams often, so that the original charts are mostly still kept.

Even if I set `textureSeamWeight = 0.00001, maxCost = 100000, iterations = 500` it still keeps large chunks of charts. Is there a way to force xatlas to break down the charts by adding more texture seams? Thanks a lot!

**Comment by jpcy** [comment]
UvMesh doesn't change texture seams at all. It finds charts/islands in UV space and packs them.

**Comment by yongsiang-fb** [comment]
> UvMesh doesn't change texture seams at all. It finds charts/islands in UV space and packs them.

Thanks for your fast response! Following your advice, I tried avoiding `UvMesh` this time and I instead made the UV coordinates as the vertex positions for the `Mesh` (i.e., the input meshes were flat rectangles representing the original input textures). But even in this case, the texture seams discovered by `xatlas` were still very large!

The only way I found that could break down the texture seams was to duplicate the vertices so each triangle became independent of each other (i.e., there were no overlapped indices between the triangles), and additionally I added a random shift to the `z` axis of each triangle (i.e., those triangles would no longer be placed on the same surface in the 3d space). But this approach would make every triangle to use a different texture seam. So the number of texture seams would be too large!

Are there some ways to break down the texture seams based on the optimal configuration that would make the size of the output atlas smallest? Thanks a lot!

**Comment by jpcy** [comment]
I don't know what you mean by the charts/atlas being too large, when you're repacking an existing UV channel. Some before and after screenshots would help.

**Comment by yongsiang-fb** [comment]
Surely. Let's say our original texture contains two islands/charts represented by the red & green part below:
![BEFORE](https://i.imgur.com/OctzWkT.png)

Because both charts/islands are quite big, the final texture width is also big no matter how we pack the the two charts.

However, if we could break down the charts into multiple ones, it's actually possible to minimize the size of the final texture without any re-scaling:
![AFTER](https://i.imgur.com/P49Aben.png)

**Comment by jpcy** [comment]
There's no option to do that. Generally unwrapped models have a wide range of chart sizes, so the small ones fit inside the larger ones with holes.
