### ISSUE TITLE
Keep original UVs?

### ISSUE THREAD

**Issue by mvijfwinkel** [jpcy/xatlas#99]
I'd like to use XAtlas to generate a secondary UV channel on some meshes (for baking a lightmap).

I'm playing with the example project that imports an OBJ. Generating the new UVs works really well, but XAtlas does not retain the original UVs. Is there an easy way to generate a new UV channel, while keeping the original UV's?  (I would export the meshes as an FBX file).

XAtlas generates new vertices, and I don't know how to map back the original UVs on the new mesh.

**Comment by jpcy** [comment]
[xatlas::Vertex::xref](https://github.com/jpcy/xatlas/blob/master/source/xatlas/xatlas.h#L64) maps back to the original vertex.
